# Build the snap on pull_request to ensure the snap is buildable before merge to main
#
# This workflow duplicates some of the logic from release-snap.yaml.  If modifying this workflow,
# ensure that release-snap.yaml is also updated
name: Test Build Snap

on:
  pull_request:

env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

jobs:
  build:
    name: Build classic snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable

      - name: Install dependencies
        run: |
          sudo snap install --classic --channel edge snapcraft          

      - name: Build Snap
        run: snapcraft pack -v